# Generated by Django 4.2 on 2023-04-28 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orden.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_cart_products'),
        ('DirEnvio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenID', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[(orden.models.OrdenStatus['CREATED'], 'CREATED'), (orden.models.OrdenStatus['PAYED'], 'PAYED'), (orden.models.OrdenStatus['COMPLETED'], 'COMPLETED'), (orden.models.OrdenStatus['CANCELED'], 'CANCELED')], default=orden.models.OrdenStatus['CREATED'], max_length=10)),
                ('envio_total', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('direccion_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DirEnvio.direccionenvio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
