# Generated by Django 4.2 on 2023-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ordenID',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
