# Generated by Django 4.2 on 2023-04-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
